name: SkyblockFly
main: me.tlwv2.skyblockfly.SkyblockFly
version: 1.0
description: Skyblock fly but toggleable
depend: [PCore, ASkyBlock]
commands:
   islandfly:
      description: Turns flying on or off or toggles it if no argument is specified (This will only work on YOUR island)
      usage: /islandfly [on:off]
      aliases: [isfly, ifly]