name: SKAdminTool
main: me.tlwv2.admintool.AdminTool
version: 1.0
depend: [PCore]
commands:
   rename:
      description: renames held item
      usage: /rename <name>
   customrules:
      description: allows changing of custom gamerules
      usage: /customrules <list:set> [rule name] [value]
      aliases: [crules, crs, cr]
   attributes:
      description: (WIP) changes attributes of held item
      usage: /attributes <add:remove:edit:list> [name] [amount] [operation]
      aliases: [attribs, as]
   setstacksize:
      description: changes amount of items of held item
      usage: /setstacksize <amount>
      aliases: [sss]
   getperms:
      description: Gets all permission nodes that match the given node
      usage: /getperms <player:group> <player name:group name> [node]
      aliases: [gps]