name: SkyblockTiers
main: me.tlwv2.skyblocktiers.SkyblockTiers
version: 1.0
description: Skyblock Mining tiers
depend: [PCore, Vault, uSkyBlock]
commands:
   miningupgrade:
      description: Opens upgrade menu
      usage: /miningupgrade
      aliases: [mupgrade, mu, smupgrade, mupg, smupg]
   settier:
      description: Sets/Views Skyblock Tiers manually
      usage: /settier <[player]:list> <tier>
      aliases: [st, sbst, sbsettier]
   testprobabilities:
      description: Allows you to test the probability to get certain ores
      usage: /testprobabilities <amount of tests> <tier level to test>
      aliases: [tprobabilities, tps, tprobs, testprobs, tprobils]