name: PCore
main: me.tlwv2.core.Core
version: 1.1
description: Stuff that I use in my plugins a lot so ye
commands:
   listdependers:
      description: Lists Plugins dependent on this one
      usage: /listdependers
      aliases: [lds, ldependers, ldeps, ld]
   phelp:
      description: Universal Patented Maxwell Help Command
      usage: /phelp [plugin]
      aliases: [ph]