name: KitsPlus
main: me.tlwv2.kitsp.Main
version: 1.0
depend: [PCore]
commands:
   kitsplus:
      description: Main KitsPlus Command
      usage: /kitsplus <add:remove:edit:list:gui:needspermissions> [display name]
      aliases: [kitsp, kp]